import requests
from typing import Any, Dict, Optional, Union
import sys
import os

# Import postprocess from the same directory
from .postprocess import vep_compact

BASE_URL = "https://rest.ensembl.org"


def _to_bool01(value: Optional[bool]) -> Optional[str]:
    if value is None:
        return None
    return "1" if value else "0"


def _get_json(url: str, params: Dict[str, Any], timeout: Optional[float] = None, return_response: bool = False) -> Any:
    headers = {"Accept": "application/json", "Content-Type": "application/json"}
    response = requests.get(url, headers=headers, params=params, timeout=timeout)
    if return_response:
        return response
    else:
        try:
            return response.json()
        except Exception:
            return response.text




def _normalize_params(params: Dict[str, Any]) -> Dict[str, Any]:
    """Convert a mapping of optional VEP params into request params.

    - Drops keys with value None
    - Converts booleans to "1"/"0" strings as required by the API
    - Leaves other types as-is
    """
    out: Dict[str, Any] = {}
    for key, val in params.items():
        if val is None:
            continue
        if isinstance(val, bool):
            conv = _to_bool01(val)
            if conv is not None:
                out[key] = conv
        else:
            out[key] = val
    return out


def vep_by_hgvs(
    hgvs_notation: str,
    species: str,
    *,
    # Real optional VEP parameters (keyword-only)
    AlphaMissense: Optional[bool] = None,
    AncestralAllele: Optional[bool] = None,
    Blosum62: Optional[bool] = None,
    CADD: Optional[Union[bool, str]] = None,
    ClinPred: Optional[bool] = None,
    Conservation: Optional[bool] = None,
    DosageSensitivity: Optional[bool] = None,
    EVE: Optional[bool] = None,
    Enformer: Optional[bool] = None,
    GO: Optional[bool] = None,
    GeneSplicer: Optional[bool] = None,
    Geno2MP: Optional[bool] = None,
    IntAct: Optional[bool] = None,
    LOEUF: Optional[bool] = None,
    LoF: Optional[bool] = None,
    MaveDB: Optional[bool] = None,
    MaxEntScan: Optional[bool] = None,
    NMD: Optional[bool] = None,
    OpenTargets: Optional[bool] = None,
    Paralogues: Optional[str] = None,
    Phenotypes: Optional[bool] = None,
    REVEL: Optional[bool] = None,
    RiboseqORFs: Optional[bool] = None,
    SpliceAI: Optional[int] = None,
    UTRAnnotator: Optional[bool] = None,
    ambiguous_hgvs: Optional[bool] = None,
    appris: Optional[bool] = None,
    callback: Optional[str] = None,
    canonical: Optional[bool] = None,
    ccds: Optional[bool] = None,
    dbNSFP: Optional[str] = None,
    dbscSNV: Optional[bool] = None,
    distance: Optional[int] = None,
    domains: Optional[bool] = None,
    failed: Optional[bool] = None,
    flag_pick: Optional[bool] = None,
    flag_pick_allele: Optional[bool] = None,
    flag_pick_allele_gene: Optional[bool] = None,
    ga4gh_vrs: Optional[bool] = None,
    gencode_basic: Optional[bool] = None,
    gencode_primary: Optional[bool] = None,
    hgvs: Optional[bool] = None,
    mane: Optional[bool] = None,
    merged: Optional[bool] = None,
    minimal: Optional[bool] = None,
    mirna: Optional[bool] = None,
    mutfunc: Optional[bool] = None,
    numbers: Optional[bool] = None,
    per_gene: Optional[bool] = None,
    pick: Optional[bool] = None,
    pick_allele: Optional[bool] = None,
    pick_allele_gene: Optional[bool] = None,
    pick_order: Optional[str] = None,
    protein: Optional[bool] = None,
    refseq: Optional[bool] = None,
    shift_3prime: Optional[bool] = None,
    shift_genomic: Optional[bool] = None,
    transcript_id: Optional[str] = None,
    transcript_version: Optional[bool] = None,
    tsl: Optional[bool] = None,
    uniprot: Optional[bool] = None,
    variant_class: Optional[bool] = None,
    vcf_string: Optional[bool] = None,
    xref_refseq: Optional[bool] = None,
    # Request controls
    timeout: Optional[float] = None,
    return_response: bool = False,
    postprocess: bool = True,
) -> Any:
    """Fetch variant consequences based on an HGVS notation.
    See docs: https://rest.ensembl.org/documentation/info/vep_hgvs_get
    """
    url = f"{BASE_URL}/vep/{species}/hgvs/{hgvs_notation}"
    params = _normalize_params({
        "AlphaMissense": AlphaMissense,
        "AncestralAllele": AncestralAllele,
        "Blosum62": Blosum62,
        "CADD": CADD,
        "ClinPred": ClinPred,
        "Conservation": Conservation,
        "DosageSensitivity": DosageSensitivity,
        "EVE": EVE,
        "Enformer": Enformer,
        "GO": GO,
        "GeneSplicer": GeneSplicer,
        "Geno2MP": Geno2MP,
        "IntAct": IntAct,
        "LOEUF": LOEUF,
        "LoF": LoF,
        "MaveDB": MaveDB,
        "MaxEntScan": MaxEntScan,
        "NMD": NMD,
        "OpenTargets": OpenTargets,
        "Paralogues": Paralogues,
        "Phenotypes": Phenotypes,
        "REVEL": REVEL,
        "RiboseqORFs": RiboseqORFs,
        "SpliceAI": SpliceAI,
        "UTRAnnotator": UTRAnnotator,
        "ambiguous_hgvs": ambiguous_hgvs,
        "appris": appris,
        "callback": callback,
        "canonical": canonical,
        "ccds": ccds,
        "dbNSFP": dbNSFP,
        "dbscSNV": dbscSNV,
        "distance": distance,
        "domains": domains,
        "failed": failed,
        "flag_pick": flag_pick,
        "flag_pick_allele": flag_pick_allele,
        "flag_pick_allele_gene": flag_pick_allele_gene,
        "ga4gh_vrs": ga4gh_vrs,
        "gencode_basic": gencode_basic,
        "gencode_primary": gencode_primary,
        "hgvs": hgvs,
        "mane": mane,
        "merged": merged,
        "minimal": minimal,
        "mirna": mirna,
        "mutfunc": mutfunc,
        "numbers": numbers,
        "per_gene": per_gene,
        "pick": pick,
        "pick_allele": pick_allele,
        "pick_allele_gene": pick_allele_gene,
        "pick_order": pick_order,
        "protein": protein,
        "refseq": refseq,
        "shift_3prime": shift_3prime,
        "shift_genomic": shift_genomic,
        "transcript_id": transcript_id,
        "transcript_version": transcript_version,
        "tsl": tsl,
        "uniprot": uniprot,
        "variant_class": variant_class,
        "vcf_string": vcf_string,
        "xref_refseq": xref_refseq,
    })

    result = _get_json(url, params, timeout=timeout, return_response=return_response)

    if postprocess:
        result = vep_compact(result)
    return result


def vep_by_id(
    id: str,
    species: str,
    *,
    AlphaMissense: Optional[bool] = None,
    AncestralAllele: Optional[bool] = None,
    Blosum62: Optional[bool] = None,
    CADD: Optional[Union[bool, str]] = None,
    ClinPred: Optional[bool] = None,
    Conservation: Optional[bool] = None,
    DosageSensitivity: Optional[bool] = None,
    EVE: Optional[bool] = None,
    Enformer: Optional[bool] = None,
    GO: Optional[bool] = None,
    GeneSplicer: Optional[bool] = None,
    Geno2MP: Optional[bool] = None,
    IntAct: Optional[bool] = None,
    LOEUF: Optional[bool] = None,
    LoF: Optional[bool] = None,
    MaveDB: Optional[bool] = None,
    MaxEntScan: Optional[bool] = None,
    NMD: Optional[bool] = None,
    OpenTargets: Optional[bool] = None,
    Paralogues: Optional[str] = None,
    Phenotypes: Optional[bool] = None,
    REVEL: Optional[bool] = None,
    RiboseqORFs: Optional[bool] = None,
    SpliceAI: Optional[int] = None,
    UTRAnnotator: Optional[bool] = None,
    ambiguous_hgvs: Optional[bool] = None,
    appris: Optional[bool] = None,
    callback: Optional[str] = None,
    canonical: Optional[bool] = None,
    ccds: Optional[bool] = None,
    dbNSFP: Optional[str] = None,
    dbscSNV: Optional[bool] = None,
    distance: Optional[int] = None,
    domains: Optional[bool] = None,
    failed: Optional[bool] = None,
    flag_pick: Optional[bool] = None,
    flag_pick_allele: Optional[bool] = None,
    flag_pick_allele_gene: Optional[bool] = None,
    ga4gh_vrs: Optional[bool] = None,
    gencode_basic: Optional[bool] = None,
    gencode_primary: Optional[bool] = None,
    hgvs: Optional[bool] = None,
    mane: Optional[bool] = None,
    merged: Optional[bool] = None,
    minimal: Optional[bool] = None,
    mirna: Optional[bool] = None,
    mutfunc: Optional[bool] = None,
    numbers: Optional[bool] = None,
    per_gene: Optional[bool] = None,
    pick: Optional[bool] = None,
    pick_allele: Optional[bool] = None,
    pick_allele_gene: Optional[bool] = None,
    pick_order: Optional[str] = None,
    protein: Optional[bool] = None,
    refseq: Optional[bool] = None,
    shift_3prime: Optional[bool] = None,
    shift_genomic: Optional[bool] = None,
    transcript_id: Optional[str] = None,
    transcript_version: Optional[bool] = None,
    tsl: Optional[bool] = None,
    uniprot: Optional[bool] = None,
    variant_class: Optional[bool] = None,
    vcf_string: Optional[bool] = None,
    xref_refseq: Optional[bool] = None,
    timeout: Optional[float] = None,
    return_response: bool = False,
    postprocess: bool = True,
) -> Any:
    """Fetch variant consequences based on a single variant identifier (GET)."""
    url = f"{BASE_URL}/vep/{species}/id/{id}"
    params = _normalize_params({
        "AlphaMissense": AlphaMissense,
        "AncestralAllele": AncestralAllele,
        "Blosum62": Blosum62,
        "CADD": CADD,
        "ClinPred": ClinPred,
        "Conservation": Conservation,
        "DosageSensitivity": DosageSensitivity,
        "EVE": EVE,
        "Enformer": Enformer,
        "GO": GO,
        "GeneSplicer": GeneSplicer,
        "Geno2MP": Geno2MP,
        "IntAct": IntAct,
        "LOEUF": LOEUF,
        "LoF": LoF,
        "MaveDB": MaveDB,
        "MaxEntScan": MaxEntScan,
        "NMD": NMD,
        "OpenTargets": OpenTargets,
        "Paralogues": Paralogues,
        "Phenotypes": Phenotypes,
        "REVEL": REVEL,
        "RiboseqORFs": RiboseqORFs,
        "SpliceAI": SpliceAI,
        "UTRAnnotator": UTRAnnotator,
        "ambiguous_hgvs": ambiguous_hgvs,
        "appris": appris,
        "callback": callback,
        "canonical": canonical,
        "ccds": ccds,
        "dbNSFP": dbNSFP,
        "dbscSNV": dbscSNV,
        "distance": distance,
        "domains": domains,
        "failed": failed,
        "flag_pick": flag_pick,
        "flag_pick_allele": flag_pick_allele,
        "flag_pick_allele_gene": flag_pick_allele_gene,
        "ga4gh_vrs": ga4gh_vrs,
        "gencode_basic": gencode_basic,
        "gencode_primary": gencode_primary,
        "hgvs": hgvs,
        "mane": mane,
        "merged": merged,
        "minimal": minimal,
        "mirna": mirna,
        "mutfunc": mutfunc,
        "numbers": numbers,
        "per_gene": per_gene,
        "pick": pick,
        "pick_allele": pick_allele,
        "pick_allele_gene": pick_allele_gene,
        "pick_order": pick_order,
        "protein": protein,
        "refseq": refseq,
        "shift_3prime": shift_3prime,
        "shift_genomic": shift_genomic,
        "transcript_id": transcript_id,
        "transcript_version": transcript_version,
        "tsl": tsl,
        "uniprot": uniprot,
        "variant_class": variant_class,
        "vcf_string": vcf_string,
        "xref_refseq": xref_refseq,
    })
    result = _get_json(url, params, timeout=timeout, return_response=return_response)
    if postprocess:
        result = vep_compact(result)
    return result


def vep_by_region(
    allele: str,
    region: str,
    species: str,
    *,
    AlphaMissense: Optional[bool] = None,
    AncestralAllele: Optional[bool] = None,
    Blosum62: Optional[bool] = None,
    CADD: Optional[Union[bool, str]] = None,
    ClinPred: Optional[bool] = None,
    Conservation: Optional[bool] = None,
    DosageSensitivity: Optional[bool] = None,
    EVE: Optional[bool] = None,
    Enformer: Optional[bool] = None,
    GO: Optional[bool] = None,
    GeneSplicer: Optional[bool] = None,
    Geno2MP: Optional[bool] = None,
    IntAct: Optional[bool] = None,
    LOEUF: Optional[bool] = None,
    LoF: Optional[bool] = None,
    MaveDB: Optional[bool] = None,
    MaxEntScan: Optional[bool] = None,
    NMD: Optional[bool] = None,
    OpenTargets: Optional[bool] = None,
    Paralogues: Optional[str] = None,
    Phenotypes: Optional[bool] = None,
    REVEL: Optional[bool] = None,
    RiboseqORFs: Optional[bool] = None,
    SpliceAI: Optional[int] = None,
    UTRAnnotator: Optional[bool] = None,
    ambiguous_hgvs: Optional[bool] = None,
    appris: Optional[bool] = None,
    callback: Optional[str] = None,
    canonical: Optional[bool] = None,
    ccds: Optional[bool] = None,
    dbNSFP: Optional[str] = None,
    dbscSNV: Optional[bool] = None,
    distance: Optional[int] = None,
    domains: Optional[bool] = None,
    failed: Optional[bool] = None,
    flag_pick: Optional[bool] = None,
    flag_pick_allele: Optional[bool] = None,
    flag_pick_allele_gene: Optional[bool] = None,
    ga4gh_vrs: Optional[bool] = None,
    gencode_basic: Optional[bool] = None,
    gencode_primary: Optional[bool] = None,
    hgvs: Optional[bool] = None,
    mane: Optional[bool] = None,
    merged: Optional[bool] = None,
    minimal: Optional[bool] = None,
    mirna: Optional[bool] = None,
    mutfunc: Optional[bool] = None,
    numbers: Optional[bool] = None,
    per_gene: Optional[bool] = None,
    pick: Optional[bool] = None,
    pick_allele: Optional[bool] = None,
    pick_allele_gene: Optional[bool] = None,
    pick_order: Optional[str] = None,
    protein: Optional[bool] = None,
    refseq: Optional[bool] = None,
    shift_3prime: Optional[bool] = None,
    shift_genomic: Optional[bool] = None,
    transcript_id: Optional[str] = None,
    transcript_version: Optional[bool] = None,
    tsl: Optional[bool] = None,
    uniprot: Optional[bool] = None,
    variant_class: Optional[bool] = None,
    vcf_string: Optional[bool] = None,
    xref_refseq: Optional[bool] = None,
    timeout: Optional[float] = None,
    return_response: bool = False,
    postprocess: bool = True,
) -> Any:
    """Fetch variant consequences for a genomic region and allele (GET).
    See docs: https://rest.ensembl.org/documentation/info/vep_region_get
    """
    url = f"{BASE_URL}/vep/{species}/region/{region}/{allele}/"
    params = _normalize_params({
        "AlphaMissense": AlphaMissense,
        "AncestralAllele": AncestralAllele,
        "Blosum62": Blosum62,
        "CADD": CADD,
        "ClinPred": ClinPred,
        "Conservation": Conservation,
        "DosageSensitivity": DosageSensitivity,
        "EVE": EVE,
        "Enformer": Enformer,
        "GO": GO,
        "GeneSplicer": GeneSplicer,
        "Geno2MP": Geno2MP,
        "IntAct": IntAct,
        "LOEUF": LOEUF,
        "LoF": LoF,
        "MaveDB": MaveDB,
        "MaxEntScan": MaxEntScan,
        "NMD": NMD,
        "OpenTargets": OpenTargets,
        "Paralogues": Paralogues,
        "Phenotypes": Phenotypes,
        "REVEL": REVEL,
        "RiboseqORFs": RiboseqORFs,
        "SpliceAI": SpliceAI,
        "UTRAnnotator": UTRAnnotator,
        "ambiguous_hgvs": ambiguous_hgvs,
        "appris": appris,
        "callback": callback,
        "canonical": canonical,
        "ccds": ccds,
        "dbNSFP": dbNSFP,
        "dbscSNV": dbscSNV,
        "distance": distance,
        "domains": domains,
        "failed": failed,
        "flag_pick": flag_pick,
        "flag_pick_allele": flag_pick_allele,
        "flag_pick_allele_gene": flag_pick_allele_gene,
        "ga4gh_vrs": ga4gh_vrs,
        "gencode_basic": gencode_basic,
        "gencode_primary": gencode_primary,
        "hgvs": hgvs,
        "mane": mane,
        "merged": merged,
        "minimal": minimal,
        "mirna": mirna,
        "mutfunc": mutfunc,
        "numbers": numbers,
        "per_gene": per_gene,
        "pick": pick,
        "pick_allele": pick_allele,
        "pick_allele_gene": pick_allele_gene,
        "pick_order": pick_order,
        "protein": protein,
        "refseq": refseq,
        "shift_3prime": shift_3prime,
        "shift_genomic": shift_genomic,
        "transcript_id": transcript_id,
        "transcript_version": transcript_version,
        "tsl": tsl,
        "uniprot": uniprot,
        "variant_class": variant_class,
        "vcf_string": vcf_string,
        "xref_refseq": xref_refseq,
    })
    result = _get_json(url, params, timeout=timeout, return_response=return_response)
    if postprocess:
        result = vep_compact(result)
    return result


